#!/usr/bin/env python3
"""Build the FEDLIGHT console.

Outputs
  dev.html              full document that links src/ files directly (edit + refresh)
  index.html            standalone full document, everything inlined
  dist/fedlight.html   artifact page body (no doctype/html/head/body — the host wraps it)

Each JS file gets its own <script> tag so a syntax error in one panel cannot take down the rest.
"""
import base64
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent
SRC = ROOT / "src"
PANEL_ORDER = [
    "terminal", "map", "countdown", "enhance", "netgraph", "trace", "decrypt",
    "sysmon", "spectrum", "radar", "face", "dossier", "alerts",
]
DOC_HEAD = (
    '<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
    '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">\n'
)


def ordered(files):
    rank = {name: i for i, name in enumerate(PANEL_ORDER)}
    return sorted(files, key=lambda p: (rank.get(p.stem, 99), p.stem))


MIME = {".gif": "image/gif", ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".webp": "image/webp"}


def gen_assets():
    """Embed src/assets/* as data URIs on HD.assets (the artifact CSP blocks external images)."""
    files = sorted(f for f in (SRC / "assets").glob("*") if f.suffix.lower() in MIME) if (SRC / "assets").exists() else []
    out = SRC / "js" / "assets.gen.js"
    if not files:
        return []
    newest = max([f.stat().st_mtime for f in files] + [pathlib.Path(__file__).stat().st_mtime])
    if not out.exists() or out.stat().st_mtime < newest:
        rows = [f"  {json.dumps(f.stem)}: 'data:{MIME[f.suffix.lower()]};base64,{base64.b64encode(f.read_bytes()).decode()}'" for f in files]
        tmp = out.with_suffix(".tmp")
        head = "/* generated by build.py from src/assets - do not edit */\nwindow.HD = window.HD || {};\nHD.assets = {\n"
        tmp.write_text(head + ",\n".join(rows) + "\n};\n", encoding="utf-8")
        tmp.replace(out)  # atomic, so parallel dev builds never read a half-written file
    return [out]


def sources():
    css = [SRC / "css" / "base.css"] + ordered((SRC / "css" / "panels").glob("*.css"))
    js = [SRC / "js" / "core.js"] + gen_assets() + sorted((SRC / "js" / "data").glob("*.js")) + ordered((SRC / "js" / "panels").glob("*.js")) + [SRC / "js" / "shell.js"]
    return [p for p in css if p.exists()], [p for p in js if p.exists()]


def rel(p):
    return p.relative_to(ROOT).as_posix()


def read(p):
    return p.read_text(encoding="utf-8")


def inline_css(files):
    parts = []
    for f in files:
        text = read(f)
        if re.search(r"</style", text, re.I):
            sys.exit(f"build: {rel(f)} contains '</style' — not inlinable")
        parts.append(f"/* ==== {rel(f)} ==== */\n{text}")
    return "<style>\n" + "\n".join(parts) + "\n</style>"


def inline_js(files):
    tags = []
    for f in files:
        text = re.sub(r"</(script)", r"<\\/\1", read(f), flags=re.I)
        tags.append(f"<script>/* ==== {rel(f)} ==== */\n{text}\n</script>")
    return "\n".join(tags)


def main():
    # --dev NAME writes only a linked dev page under that name (lets parallel builders avoid races)
    dev_only = sys.argv[sys.argv.index("--dev") + 1] if "--dev" in sys.argv else None
    shell = read(SRC / "shell.html")
    head, body = shell.split("<!--@BODY-->")
    css_files, js_files = sources()

    styles_inline = inline_css(css_files)
    scripts_inline = inline_js(js_files)
    styles_linked = "\n".join(f'<link rel="stylesheet" href="{rel(f)}">' for f in css_files)
    scripts_linked = "\n".join(f'<script src="{rel(f)}"></script>' for f in js_files)

    def page(styles, scripts, wrap):
        h = head.replace("<!--@STYLES-->", styles).strip()
        b = body.replace("<!--@SCRIPTS-->", scripts).strip()
        if wrap:
            return f"{DOC_HEAD}{h}\n</head>\n<body>\n{b}\n</body>\n</html>\n"
        return f"{h}\n{b}\n"

    if dev_only:
        (ROOT / dev_only).write_text(page(styles_linked, scripts_linked, True), encoding="utf-8")
        print(f"dev page ok - {dev_only}")
        return
    (ROOT / "dev.html").write_text(page(styles_linked, scripts_linked, True), encoding="utf-8")
    (ROOT / "index.html").write_text(page(styles_inline, scripts_inline, True), encoding="utf-8")
    (ROOT / "dist").mkdir(exist_ok=True)
    art = page(styles_inline, scripts_inline, False)
    (ROOT / "dist" / "fedlight.html").write_text(art, encoding="utf-8")

    panels = [p.stem for p in js_files if p.parent.name == "panels"]
    print(f"build ok - {len(css_files)} css - {len(js_files)} js - panels: {', '.join(panels) or '(none)'}")
    print(f"artifact size: {len(art.encode('utf-8')) / 1024:.1f} KB")


if __name__ == "__main__":
    main()
